import { FormEvent, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { CheckCircle2, LockKeyhole, Radar, ShieldCheck, Sparkles } from 'lucide-react'
import { api } from '../api/client'
import type { AuthResponse } from '../types'

export default function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const nav = useNavigate()
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); setLoading(true); try { const payload = mode === 'register' ? { name, email, password } : { email, password }; const { data } = await api.post<AuthResponse>(`/auth/${mode}`, payload); localStorage.setItem('devguard_token', data.access_token); localStorage.setItem('devguard_user', JSON.stringify(data.user)); nav('/') } catch (err:any) { setError(err.response?.data?.detail || 'Something went wrong') } finally { setLoading(false) } }
  return <div className="auth-page">
    <div className="auth-showcase"><div className="showcase-glow"/><div className="auth-logo large"><div className="brand-mark"><ShieldCheck size={26}/></div><span>DevGuard AI</span></div><p className="eyebrow">Security intelligence for developers</p><h1>Ship cleaner code.<br/>Catch risk earlier.</h1><p className="showcase-copy">A local-first review workspace for static code analysis, risk scoring, remediation guidance and exportable engineering reports.</p><div className="showcase-features"><div><Radar/><span><b>Deterministic scanning</b><small>Fast, explainable security rules</small></span></div><div><Sparkles/><span><b>AI-ready reviews</b><small>Optional deep-review layer</small></span></div><div><CheckCircle2/><span><b>Audit-ready reports</b><small>PDF, HTML, JSON, CSV and more</small></span></div></div></div>
    <div className="auth-side"><div className="auth-card"><div className="secure-pill"><LockKeyhole size={14}/> Secure local workspace</div><h1>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h1><p>{mode === 'login' ? 'Sign in to review code and track findings.' : 'Start scanning code for security and quality issues.'}</p><form onSubmit={submit}>{mode === 'register' && <label>Name<input value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label>{error&&<div className="error-box">{error}</div>}<button className="primary auth-submit" disabled={loading}>{loading?'Please wait…':mode==='login'?'Sign in to DevGuard':'Create account'}</button></form><div className="auth-switch">{mode==='login'?<>New here? <a href="/register">Create an account</a></>:<>Already have an account? <a href="/login">Sign in</a></>}</div></div></div>
  </div>
}
